CREATE TABLE [User]
(
	[Id] INT NOT NULL PRIMARY KEY, 
    [Name] NCHAR(100) NULL, 
    [Password] NCHAR(100) NOT NULL, 
    [Role] INT NOT NULL FOREIGN KEY([Id]) REFERENCES Role (Id),
    [Email] NCHAR(100) NOT NULL, 
    [Test] NCHAR(10) NOT NULL
)

